"use client";

import * as React from "react";
import Link from "next/link";
import { toast } from "sonner";
import { UploadZone } from "@/components/tool-shell/upload-zone";
import { ActionBar, type ActionState } from "@/components/tool-shell/action-bar";
import { ProgressRing } from "@/components/tool-shell/progress-ring";
import { ServerSideNotice } from "@/components/tool-shell/client-badge";
import { OcrFallbackPrompt } from "@/components/tools/ocr-fallback-prompt";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useTextExtraction } from "@/lib/ai/use-text-extraction";
import { buildQuestionsHtml, buildAnswerKeyHtml, buildQuizText } from "@/lib/ai/quiz-pdf";
import type { McqQuestion, McqDifficulty } from "@/lib/ai/provider";
import { downloadBlob, cn } from "@/lib/utils";
import { SITE_NAME } from "@/lib/constants";
import type { ToolDefinition } from "@/lib/tools";

const LIMITS = { maxPages: 50, maxCharacters: 100_000 };
const LETTERS = ["A", "B", "C", "D"];

export function McqPdfTool({ tool }: { tool: ToolDefinition }) {
  const [file, setFile] = React.useState<File | null>(null);
  const [count, setCount] = React.useState(10);
  const [difficulty, setDifficulty] = React.useState<McqDifficulty>("medium");
  const [includeAnswerKey, setIncludeAnswerKey] = React.useState(true);
  const [revealed, setRevealed] = React.useState<Set<number>>(new Set());

  const extraction = useTextExtraction(LIMITS);
  const [state, setState] = React.useState<ActionState>("idle");
  const [progress, setProgress] = React.useState(0);
  const [questions, setQuestions] = React.useState<McqQuestion[] | null>(null);
  const [errorMessage, setErrorMessage] = React.useState<string | null>(null);

  function handleFiles(files: File[]) {
    const f = files[0] ?? null;
    setFile(f);
    setQuestions(null);
    setRevealed(new Set());
    setErrorMessage(null);
    setState("idle");
    extraction.reset();
  }

  function toggleReveal(index: number) {
    setRevealed((prev) => {
      const next = new Set(prev);
      if (next.has(index)) next.delete(index);
      else next.add(index);
      return next;
    });
  }

  async function runGenerate(text: string) {
    setState("processing");
    setProgress(0.9);
    setErrorMessage(null);
    try {
      const res = await fetch("/api/ai/mcq", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text, count, difficulty }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Question generation failed");
      setQuestions(data.questions);
      setRevealed(new Set());
      setProgress(1);
      setState("done");
    } catch (err) {
      console.error(err);
      setState("error");
      setErrorMessage(err instanceof Error ? err.message : "Something went wrong.");
      toast.error("Couldn't generate questions", {
        description: err instanceof Error ? err.message : undefined,
      });
    }
  }

  async function handleGenerate() {
    if (!file) return;
    setErrorMessage(null);
    const text = await extraction.start(file);
    if (text) await runGenerate(text);
  }

  async function handleRunOcr() {
    const text = await extraction.runOcr();
    if (text) await runGenerate(text);
  }

  const isReading = extraction.phase === "extracting" || extraction.phase === "ocr-running";
  const isBusy = isReading || state === "processing";
  const busyLabel = isReading ? extraction.statusText : "Generating questions…";
  const busyProgress = isReading ? extraction.progress * 100 : progress * 100;
  const displayError =
    state === "error" ? errorMessage : extraction.phase === "error" ? extraction.error : null;

  function downloadTxt() {
    if (!questions) return;
    downloadBlob(
      new Blob([buildQuizText(questions, includeAnswerKey)], { type: "text/plain" }),
      "quiz.txt"
    );
  }

  async function downloadPdf() {
    if (!questions) return;
    const { renderHtmlToPdf } = await import("@/lib/pdf/html-to-pdf-render");
    const { PDFDocument } = await import("@cantoo/pdf-lib");

    const pdfOpts = {
      pageSize: "a4" as const,
      orientation: "portrait" as const,
      marginMm: 20,
      footer: { text: `Generated by ${SITE_NAME}`, showPageNumbers: true },
    };
    const questionsBytes = await renderHtmlToPdf(buildQuestionsHtml(questions), pdfOpts);

    // Rendered as a fully separate PDF and merged in, rather than appended to
    // the same HTML flow — html2canvas/jsPDF's pagination slices by pixel
    // height, not CSS page-break rules, so this is the only way to guarantee
    // the answer key genuinely starts on its own page regardless of how many
    // pages the questions ended up taking.
    const finalDoc = await PDFDocument.load(questionsBytes);
    if (includeAnswerKey) {
      const answerKeyBytes = await renderHtmlToPdf(buildAnswerKeyHtml(questions), pdfOpts);
      const answerKeyDoc = await PDFDocument.load(answerKeyBytes);
      const copiedPages = await finalDoc.copyPages(answerKeyDoc, answerKeyDoc.getPageIndices());
      copiedPages.forEach((p) => finalDoc.addPage(p));
    }

    const mergedBytes = await finalDoc.save();
    downloadBlob(new Blob([new Uint8Array(mergedBytes)], { type: "application/pdf" }), "quiz.pdf");
  }

  return (
    <div className="mx-auto max-w-2xl px-4 pb-40 pt-4 md:pb-16">
      <div className="mb-4 space-y-2">
        <ServerSideNotice>
          This tool sends your document&apos;s text to Google&apos;s Gemini API for
          processing. See our{" "}
          <Link href="/privacy" className="underline underline-offset-2">
            privacy policy
          </Link>
          .
        </ServerSideNotice>
      </div>

      {!file ? (
        <UploadZone accept={tool.accept} multiple={false} maxFiles={1} onFiles={handleFiles} acceptHint="One file at a time" />
      ) : isBusy ? (
        <div className="flex flex-col items-center justify-center gap-4 rounded-2xl border border-border bg-muted/30 py-12">
          <ProgressRing progress={busyProgress} />
          <p className="text-sm text-muted-foreground">{busyLabel}</p>
        </div>
      ) : extraction.phase === "needs-ocr" ? (
        <OcrFallbackPrompt
          onRunOcr={handleRunOcr}
          onCancel={() => {
            setFile(null);
            extraction.reset();
          }}
        />
      ) : questions ? (
        <div className="space-y-4">
          <div className="space-y-3">
            {questions.map((q, i) => (
              <div key={i} className="space-y-2 rounded-xl border border-border bg-card p-4">
                <p className="font-medium">
                  {i + 1}. {q.question}
                </p>
                <div className="space-y-1">
                  {q.options.map((opt, j) => (
                    <div
                      key={j}
                      className={cn(
                        "rounded-lg border px-3 py-2 text-sm",
                        revealed.has(i) && j === q.correctIndex
                          ? "border-emerald-500 bg-emerald-500/10 font-medium"
                          : "border-border"
                      )}
                    >
                      {LETTERS[j]}. {opt}
                    </div>
                  ))}
                </div>
                <button
                  type="button"
                  className="text-xs font-medium text-primary"
                  onClick={() => toggleReveal(i)}
                >
                  {revealed.has(i) ? "Hide answer" : "Show answer"}
                </button>
              </div>
            ))}
          </div>

          <div className="flex gap-2">
            <Button variant="outline" className="flex-1" onClick={downloadTxt}>
              Download .txt
            </Button>
            <Button className="flex-1" onClick={downloadPdf}>
              Download PDF
            </Button>
          </div>

          <button
            type="button"
            onClick={() => {
              setFile(null);
              setQuestions(null);
              setState("idle");
            }}
            className="mx-auto block text-sm font-medium text-muted-foreground underline-offset-4 hover:underline"
          >
            Generate another quiz
          </button>
        </div>
      ) : (
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label htmlFor="mcq-count">Number of questions</Label>
              <Input
                id="mcq-count"
                type="number"
                min={1}
                max={20}
                value={count}
                onChange={(e) => setCount(Math.min(20, Math.max(1, Number(e.target.value) || 1)))}
              />
            </div>
            <div className="space-y-1.5">
              <Label>Difficulty</Label>
              <Select value={difficulty} onValueChange={(v) => setDifficulty(v as McqDifficulty)}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="easy">Easy</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="hard">Hard</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <label className="flex items-center gap-2 text-sm">
            <Checkbox checked={includeAnswerKey} onCheckedChange={(v) => setIncludeAnswerKey(v === true)} />
            Include answer key
          </label>
        </div>
      )}

      {displayError && (
        <p className="mt-3 rounded-lg bg-destructive/10 px-3 py-2 text-sm text-destructive">{displayError}</p>
      )}

      {state !== "done" && file && extraction.phase !== "needs-ocr" && !isBusy && (
        <ActionBar state={state === "idle" ? "ready" : state} label="Generate MCQs" progress={progress * 100} onAction={handleGenerate} />
      )}
    </div>
  );
}
