import {
  FileType,
  FileSpreadsheet,
  Presentation,
  ImageIcon,
  FileText,
  Globe,
  Combine,
  Scissors,
  FileOutput,
  FileMinus,
  RotateCw,
  ListOrdered,
  Minimize2,
  Wrench,
  ScanText,
  Type,
  Highlighter,
  Hash,
  Stamp,
  PanelTop,
  Lock,
  Unlock,
  PenTool,
  EyeOff,
  MessageSquare,
  BookOpen,
  Languages,
  Table,
  type LucideIcon,
} from "lucide-react";
import type { CategorySlug } from "./categories";

/** react-dropzone-style accept map: MIME type -> file extensions */
export type AcceptMap = Record<string, string[]>;

export interface ToolDefinition {
  slug: string;
  name: string;
  /** Short label for the 2-column home grid card */
  shortName: string;
  category: CategorySlug;
  description: string;
  icon: LucideIcon;
  isPro: boolean;
  /** True when the whole pipeline runs in-browser (shows the "never leaves your device" badge) */
  isClientSide: boolean;
  /** False = ToolShell renders with a TODO panel instead of a working action */
  isImplemented: boolean;
  accept: AcceptMap;
  multiple: boolean;
  maxFiles: number;
  /** File name suffix / extension used for the result download, e.g. "merged.pdf" */
  resultFileName: string;
  keywords: string[];
}

const PDF_ACCEPT: AcceptMap = { "application/pdf": [".pdf"] };
const IMAGE_ACCEPT: AcceptMap = {
  "image/jpeg": [".jpg", ".jpeg"],
  "image/png": [".png"],
  "image/webp": [".webp"],
};

export const tools: ToolDefinition[] = [
  // ---------- Convert ----------
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    shortName: "PDF → Word",
    category: "convert",
    description: "Convert PDF documents into editable Word (.docx) files.",
    icon: FileType,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "converted.docx",
    keywords: ["word", "docx", "export"],
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    shortName: "PDF → Excel",
    category: "convert",
    description: "Extract tables from a PDF into an Excel spreadsheet.",
    icon: FileSpreadsheet,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "converted.xlsx",
    keywords: ["excel", "xlsx", "spreadsheet", "tables"],
  },
  {
    slug: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    shortName: "PDF → PPT",
    category: "convert",
    description: "Turn PDF pages into an editable PowerPoint presentation.",
    icon: Presentation,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "converted.pptx",
    keywords: ["powerpoint", "pptx", "slides"],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    shortName: "PDF → JPG",
    category: "convert",
    description: "Export every page of a PDF as a high-quality JPG image.",
    icon: ImageIcon,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "pages.zip",
    keywords: ["jpg", "jpeg", "image", "export"],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    shortName: "Word → PDF",
    category: "convert",
    description: "Convert .docx documents into shareable PDF files.",
    icon: FileText,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: {
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
        [".docx"],
    },
    multiple: false,
    maxFiles: 1,
    resultFileName: "converted.pdf",
    keywords: ["word", "docx", "import"],
  },
  {
    slug: "excel-to-pdf",
    name: "Excel to PDF",
    shortName: "Excel → PDF",
    category: "convert",
    description: "Convert spreadsheets into print-ready PDF files.",
    icon: FileSpreadsheet,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: {
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [
        ".xlsx",
      ],
    },
    multiple: false,
    maxFiles: 1,
    resultFileName: "converted.pdf",
    keywords: ["excel", "xlsx", "spreadsheet"],
  },
  {
    slug: "ppt-to-pdf",
    name: "PowerPoint to PDF",
    shortName: "PPT → PDF",
    category: "convert",
    description: "Convert presentations into a shareable PDF.",
    icon: Presentation,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: {
      "application/vnd.openxmlformats-officedocument.presentationml.presentation":
        [".pptx"],
    },
    multiple: false,
    maxFiles: 1,
    resultFileName: "converted.pdf",
    keywords: ["powerpoint", "pptx", "slides"],
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    shortName: "JPG → PDF",
    category: "convert",
    description: "Combine one or more images into a single PDF.",
    icon: ImageIcon,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: IMAGE_ACCEPT,
    multiple: true,
    maxFiles: 50,
    resultFileName: "images.pdf",
    keywords: ["jpg", "jpeg", "png", "image", "import"],
  },
  {
    slug: "html-to-pdf",
    name: "HTML to PDF",
    shortName: "HTML → PDF",
    category: "convert",
    description: "Render a web page or HTML file as a PDF document.",
    icon: Globe,
    isPro: true,
    isClientSide: false,
    isImplemented: false,
    accept: { "text/html": [".html", ".htm"] },
    multiple: false,
    maxFiles: 1,
    resultFileName: "page.pdf",
    keywords: ["html", "web", "url"],
  },

  // ---------- Organize ----------
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    shortName: "Merge PDF",
    category: "organize",
    description: "Combine multiple PDFs into one document, in any order.",
    icon: Combine,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: true,
    maxFiles: 50,
    resultFileName: "merged.pdf",
    keywords: ["combine", "join"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    shortName: "Split PDF",
    category: "organize",
    description: "Split a PDF into separate files by page range.",
    icon: Scissors,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "split.zip",
    keywords: ["divide", "separate"],
  },
  {
    slug: "extract-pages",
    name: "Extract Pages",
    shortName: "Extract Pages",
    category: "organize",
    description: "Pull specific pages out of a PDF into a new file.",
    icon: FileOutput,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "extracted.pdf",
    keywords: ["pull", "pages"],
  },
  {
    slug: "remove-pages",
    name: "Remove Pages",
    shortName: "Remove Pages",
    category: "organize",
    description: "Delete unwanted pages from a PDF document.",
    icon: FileMinus,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "pages-removed.pdf",
    keywords: ["delete", "pages"],
  },
  {
    slug: "rotate-pages",
    name: "Rotate Pages",
    shortName: "Rotate Pages",
    category: "organize",
    description: "Rotate one, several, or all pages of a PDF.",
    icon: RotateCw,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "rotated.pdf",
    keywords: ["turn", "orientation"],
  },
  {
    slug: "reorder-pages",
    name: "Reorder Pages",
    shortName: "Reorder Pages",
    category: "organize",
    description: "Drag and drop page thumbnails to change their order.",
    icon: ListOrdered,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "reordered.pdf",
    keywords: ["drag", "order", "arrange"],
  },

  // ---------- Optimize ----------
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    shortName: "Compress PDF",
    category: "optimize",
    description: "Shrink file size with low, recommended or extreme presets.",
    icon: Minimize2,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "compressed.pdf",
    keywords: ["shrink", "size", "reduce"],
  },
  {
    slug: "repair-pdf",
    name: "Repair PDF",
    shortName: "Repair PDF",
    category: "optimize",
    description: "Attempt to fix a corrupted or damaged PDF file.",
    icon: Wrench,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "repaired.pdf",
    keywords: ["fix", "corrupt", "damaged"],
  },
  {
    slug: "ocr-pdf",
    name: "OCR Scanned PDF",
    shortName: "OCR PDF",
    category: "optimize",
    description: "Make scanned PDFs searchable and selectable with OCR.",
    icon: ScanText,
    isPro: true,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "ocr.pdf",
    keywords: ["scan", "text recognition"],
  },

  // ---------- Edit ----------
  {
    slug: "add-text-image",
    name: "Add Text & Images",
    shortName: "Add Text/Image",
    category: "edit",
    description: "Place text boxes and images anywhere on a PDF page.",
    icon: Type,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "edited.pdf",
    keywords: ["text", "image", "insert"],
  },
  {
    slug: "annotate-pdf",
    name: "Annotate & Highlight",
    shortName: "Annotate",
    category: "edit",
    description: "Highlight, draw and add sticky notes on any page.",
    icon: Highlighter,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "annotated.pdf",
    keywords: ["highlight", "draw", "markup", "comment"],
  },
  {
    slug: "add-page-numbers",
    name: "Add Page Numbers",
    shortName: "Page Numbers",
    category: "edit",
    description: "Insert page numbers with custom position and style.",
    icon: Hash,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "numbered.pdf",
    keywords: ["numbers", "pagination"],
  },
  {
    slug: "add-watermark",
    name: "Add Watermark",
    shortName: "Watermark",
    category: "edit",
    description: "Stamp a text or image watermark across every page.",
    icon: Stamp,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "watermarked.pdf",
    keywords: ["stamp", "brand", "logo"],
  },
  {
    slug: "add-header-footer",
    name: "Add Header & Footer",
    shortName: "Header/Footer",
    category: "edit",
    description: "Add repeating header or footer text to every page.",
    icon: PanelTop,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "with-header.pdf",
    keywords: ["header", "footer"],
  },

  // ---------- Security ----------
  {
    slug: "password-protect",
    name: "Password Protect",
    shortName: "Add Password",
    category: "security",
    description: "Encrypt a PDF with a password so only you can open it.",
    icon: Lock,
    isPro: false,
    isClientSide: true,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "protected.pdf",
    keywords: ["encrypt", "lock", "secure"],
  },
  {
    slug: "unlock-pdf",
    name: "Unlock PDF",
    shortName: "Unlock PDF",
    category: "security",
    description: "Remove a known password from a protected PDF.",
    icon: Unlock,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "unlocked.pdf",
    keywords: ["decrypt", "remove password"],
  },
  {
    slug: "esign-pdf",
    name: "eSign PDF",
    shortName: "eSign",
    category: "security",
    description: "Draw your signature and place it anywhere on a page.",
    icon: PenTool,
    isPro: false,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "signed.pdf",
    keywords: ["signature", "sign"],
  },
  {
    slug: "redact-pdf",
    name: "Redact PDF",
    shortName: "Redact",
    category: "security",
    description: "Permanently black out sensitive text or areas.",
    icon: EyeOff,
    isPro: true,
    isClientSide: false,
    isImplemented: false,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "redacted.pdf",
    keywords: ["hide", "censor", "black out"],
  },

  // ---------- AI Tools ----------
  {
    slug: "chat-with-pdf",
    name: "Chat with PDF",
    shortName: "Chat with PDF",
    category: "ai",
    description: "Ask questions about a document and get instant answers.",
    icon: MessageSquare,
    isPro: true,
    isClientSide: false,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "",
    keywords: ["ai", "chat", "questions", "claude"],
  },
  {
    slug: "summarize-pdf",
    name: "Summarize PDF",
    shortName: "Summarize",
    category: "ai",
    description: "Generate a concise AI summary of a long document.",
    icon: BookOpen,
    isPro: true,
    isClientSide: false,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "summary.txt",
    keywords: ["ai", "summary", "tldr", "claude"],
  },
  {
    slug: "translate-pdf",
    name: "Translate PDF",
    shortName: "Translate",
    category: "ai",
    description: "Translate the contents of a PDF into another language.",
    icon: Languages,
    isPro: true,
    isClientSide: false,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "translated.txt",
    keywords: ["ai", "language", "claude"],
  },
  {
    slug: "extract-data-csv",
    name: "Extract Data to CSV",
    shortName: "Extract to CSV",
    category: "ai",
    description: "Pull tables and structured data out of a PDF as CSV.",
    icon: Table,
    isPro: true,
    isClientSide: false,
    isImplemented: true,
    accept: PDF_ACCEPT,
    multiple: false,
    maxFiles: 1,
    resultFileName: "data.csv",
    keywords: ["ai", "csv", "table", "data", "claude"],
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: CategorySlug): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}

export function searchTools(query: string): ToolDefinition[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return tools.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.toLowerCase().includes(q))
  );
}

export function getAllToolSlugs(): string[] {
  return tools.map((t) => t.slug);
}
